objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>CodigoERP__c</fullName>
        <externalId>true</externalId>
        <label>Código ERP</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>StatusIntegracao__c</fullName>
        <label>Status Integração</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>StatusIntegracao</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/ByPass__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Obj para controle de validacao</description>
    <label>ByPass</label>
    <fields>
        <fullName>DesativarRegrasValidacao__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Desativar regras de validação</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

globalValueSets/StatusIntegracao.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Integrado com erro</fullName>
        <default>true</default>
        <label>Integrado com erro</label>
    </customValue>
    <customValue>
        <fullName>Integrado com sucesso</fullName>
    </customValue>
    <customValue>
        <fullName>Não necessario</fullName>
    </customValue>
    <customValue>
        <fullName>Pendente</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelado com sucesso</fullName>
    </customValue>
    <masterLabel>StatusIntegracao</masterLabel>
</GlobalValueSet>

classes/DwAccountIntegrableBatchTest.cls
@IsTest
public class DwAccountIntegrableBatchTest {
	private static String CLASS_NAME = 'DwAccountIntegrableBatchTest';
    
    @testSetup static void setup() {
         
        ByPass__c setting = new ByPass__c();
        setting.DesativarRegrasValidacao__c = true;
        
        insert setting;
        
        String METHOD_NAME = 'setup';
        
        Test.setMock(HttpCalloutMock.class, new DWAccIntegrableMock());
       
        Account acc = new Account(name = 'teste',
                                  Description='107'
                                  );
        
        insert acc;
        Account acc2 = new Account(name = 'teste',
                                   Description='107',
                                   CodigoERP__c='idERP'
                                   
                                  );
        insert acc2;
    
    }
    
    static testMethod void runInSyncMode(){
        Test.setMock(HttpCalloutMock.class, new DWAccIntegrableMock());
        String METHOD_NAME = 'runInSyncMode';
        
        List<Account> listAcc = [
            SELECT
            Id
            FROM Account WHERE CodigoERP__C = ''
        ];
        List<String> listAccInsert = new List<String>();
        
        listAccInsert.add(listAcc[0].id);
        
        Test.startTest();
        DwAccountIntegrableBatch.testQA(listAccInsert);
        Test.stopTest();
       	
        //descomentar quando for alterar a classe teste, é importante teste esse validação
        //System.assertEquals('Integrado com Sucesso', qtCheck.StatusIntegracao__c, 'Status da Integração atualizado corretamente');
    }
    static testMethod void runInSyncModeTwo(){
        Test.setMock(HttpCalloutMock.class, new DWAccIntegrableMock());
        String METHOD_NAME = 'runInSyncMode';
        
       List<Account> listAcc = [
            SELECT
            Id
            FROM Account WHERE CodigoERP__C != ''
        ];
        List<String> listAccInsert = new List<String>();
        
        listAccInsert.add(listAcc[0].id);
        
        Test.startTest();
        DwAccountIntegrableBatch.testQA(listAccInsert);
        Test.stopTest();
       //descomentar quando for alterar a classe teste, é importante teste esse validação
        //System.assertEquals('Integrado com Sucesso', qtCheck.StatusIntegracao__c, 'Status da Integração atualizado corretamente');
    }
    static testMethod void cancelThisSchedule(){
        String METHOD_NAME = 'cancelThisSchedule';
        
        List<Account> listQT = [
            SELECT
            Id
            FROM Account
        ];
        
        Test.startTest();
        DwAccountIntegrableBatch.cancelThisSchedule();
        Test.stopTest();
         
    }
    static testMethod void batchclass(){
        String METHOD_NAME = 'batchAcc';
        
        List<Account> listQT = [
            SELECT
            Id
            FROM Account
        ];
        
        Test.startTest();
        DwAccountIntegrableBatch obj = new DwAccountIntegrableBatch();
        DataBase.executeBatch(obj);  
        Test.stopTest();
        
    }
    static testMethod void assynclass(){
        String METHOD_NAME = 'batchAcc';
        
        List<Account> listQT = [
            SELECT
            Id
            FROM Account
        ];
        
        Test.startTest();
        DwAccountIntegrableBatch.scheduleThisClass(null);
        Test.stopTest();
        
    }
     
    
}