objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>CodigoExterno__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Usado para UBS</inlineHelpText>
        <label>Código Externo</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>QuantidadeResposta__c</fullName>
        <label>Quantidade de Resposta</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QuantidadeRespostasFinalizadas__c</fullName>
        <label>Quantidade de Respostas finalizadas</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Ambiente__c.object
<CustomObject>
    <label>Ambiente</label>
    <nameField>
        <label>Nome do ambiente</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ambientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>UBS__c</fullName>
        <label>UBS</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ambientes</relationshipLabel>
        <relationshipName>Ambientes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tipo__c</fullName>
        <label>Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Almoxarifado</fullName>
                </value>
                <value>
                    <fullName>Área Descoberta / Playground</fullName>
                </value>
                <value>
                    <fullName>BWC</fullName>
                </value>
                <value>
                    <fullName>Circulação</fullName>
                </value>
                <value>
                    <fullName>Cisterna</fullName>
                </value>
                <value>
                    <fullName>Consultório</fullName>
                </value>
                <value>
                    <fullName>Consultório Odontológico</fullName>
                </value>
                <value>
                    <fullName>Copa</fullName>
                </value>
                <value>
                    <fullName>Depósito de Materiais de Limpeza</fullName>
                </value>
                <value>
                    <fullName>Depósito de Resíduos</fullName>
                </value>
                <value>
                    <fullName>Embarque e Desembarque de Ambulância</fullName>
                </value>
                <value>
                    <fullName>Estacionamento</fullName>
                </value>
                <value>
                    <fullName>Estocagem/Dipensação de Medicamentos</fullName>
                </value>
                <value>
                    <fullName>Expurgo</fullName>
                </value>
                <value>
                    <fullName>Jardim</fullName>
                </value>
                <value>
                    <fullName>Outros (descrever)</fullName>
                </value>
                <value>
                    <fullName>Sala de Administração&quot;,</fullName>
                </value>
                <value>
                    <fullName>Sala de Atividades Coletivas</fullName>
                </value>
                <value>
                    <fullName>Sala de Coleta</fullName>
                </value>
                <value>
                    <fullName>Sala de Curativos</fullName>
                </value>
                <value>
                    <fullName>Sala de Esterelização</fullName>
                </value>
                <value>
                    <fullName>Sala de Inalação</fullName>
                </value>
                <value>
                    <fullName>Sala de Observação / Procedimentos</fullName>
                </value>
                <value>
                    <fullName>Sala de Recepção/Espera</fullName>
                </value>
                <value>
                    <fullName>Sala de Vacinas</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grupo__c</fullName>
        <label>Grupo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contato__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contato</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Ambientes</relationshipLabel>
        <relationshipName>Ambientes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unidade__c</fullName>
        <label>Unidade</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cobertura__c</fullName>
        <label>Cobertura</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Coberto</fullName>
                </value>
                <value>
                    <fullName>Descoberto</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PeDireito__c</fullName>
        <label>Pé direito</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Comprimento__c</fullName>
        <label>Comprimento</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AreaAmbiente__c</fullName>
        <label>Área do ambiente</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AreaEsquadrias__c</fullName>
        <label>Área de esquadrias</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LarguraDimensao__c</fullName>
        <label>Largura</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QuantidadeResposta__c</fullName>
        <label>Quantidade de Resposta</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QuantidadeRespostasFinalizadas__c</fullName>
        <label>Quantidade de Respostas finalizadas</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Senha__c</fullName>
        <label>Senha</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EnviarEmailRecuperacao__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enviar email recuperação</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Questionario__c.object
<CustomObject>
    <label>Questionário</label>
    <nameField>
        <displayFormat>Q - {00000}</displayFormat>
        <label>Questionário</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questionários</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Secao__c</fullName>
        <label>Seção</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pergunta__c</fullName>
        <label>Pergunta</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Categoria__c</fullName>
        <label>Categoria</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Projeto</fullName>
                </value>
                <value>
                    <fullName>Ambiente</fullName>
                </value>
                <value>
                    <fullName>Edificação</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Observacao__c</fullName>
        <label>Observação</label>
        <length>130000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TextoAjuda__c</fullName>
        <label>Texto de ajuda</label>
        <length>130000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Subcategoria__c</fullName>
        <label>Subcategoria</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Categoria__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Acessibilidade</fullName>
                </value>
                <value>
                    <fullName>Comunição e usuário</fullName>
                </value>
                <value>
                    <fullName>Conforto acústico</fullName>
                </value>
                <value>
                    <fullName>Conforto térmico</fullName>
                </value>
                <value>
                    <fullName>Conforto visual</fullName>
                </value>
                <value>
                    <fullName>Custos</fullName>
                </value>
                <value>
                    <fullName>Documentação</fullName>
                </value>
                <value>
                    <fullName>Espaços</fullName>
                </value>
                <value>
                    <fullName>Gestão e manutenção</fullName>
                </value>
                <value>
                    <fullName>Infraestrutura</fullName>
                </value>
                <value>
                    <fullName>Local de uso e ocupação</fullName>
                </value>
                <value>
                    <fullName>Materiais e acabamentos</fullName>
                </value>
                <value>
                    <fullName>Mobilidade</fullName>
                </value>
                <value>
                    <fullName>Promoção e saúde</fullName>
                </value>
                <value>
                    <fullName>Segurança</fullName>
                </value>
                <value>
                    <fullName>Sociais e culturais</fullName>
                </value>
                <value>
                    <fullName>Sustentabilidade</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ItemPrincipal__c</fullName>
        <label>Item Principal</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ItemPrincipalPai__c</fullName>
        <formula>ISBLANK(ItemPrincipal__c )</formula>
        <label>Item principal pai</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Resposta__c.object
<CustomObject>
    <label>Resposta</label>
    <nameField>
        <displayFormat>R - {00000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Respostas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Secao__c</fullName>
        <formula>Pergunta__r.Secao__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Seção</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unidade__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unidade</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Respostas</relationshipLabel>
        <relationshipName>Respostas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ambiente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ambiente</label>
        <referenceTo>Ambiente__c</referenceTo>
        <relationshipLabel>Respostas</relationshipLabel>
        <relationshipName>Respostas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pergunta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pergunta</label>
        <referenceTo>Questionario__c</referenceTo>
        <relationshipLabel>Respostas</relationshipLabel>
        <relationshipName>Respostas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resposta__c</fullName>
        <label>Resposta</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RespostaUBS</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Categoria__c</fullName>
        <formula>TEXT(Pergunta__r.Categoria__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Categoria</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Observacao__c</fullName>
        <label>Observação</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SubCategoria__c</fullName>
        <formula>TEXT(Pergunta__r.Subcategoria__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SubCategoria</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ItemPrincipal__c</fullName>
        <formula>Pergunta__r.ItemPrincipal__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Item principal</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RespostaRealizada__c</fullName>
        <formula>IF(ISBLANK( TEXT(Resposta__c) ) ,&quot;&quot;, &quot;✅&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Resposta realizada</label>
        <type>Text</type>
    </fields>
</CustomObject>

globalValueSets/RespostaUBS.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Péssimo</fullName>
    </customValue>
    <customValue>
        <fullName>Ruim</fullName>
    </customValue>
    <customValue>
        <fullName>Regular</fullName>
    </customValue>
    <customValue>
        <fullName>Bom</fullName>
    </customValue>
    <customValue>
        <fullName>Excelente</fullName>
    </customValue>
    <customValue>
        <fullName>Não se aplica</fullName>
    </customValue>
    <description>Péssimo, Ruim, Regular, Bom, Excelente / Não se aplica</description>
    <masterLabel>Resposta UBS</masterLabel>
</GlobalValueSet>

classes/ControllerAuthLwc.cls
public without sharing class ControllerAuthLwc {
    
    @AuraEnabled
    public static String accountDeleteRecMethod(String recordId,String ctRelationRecordRec){
    try {
        AccountContactRelation ctRelation = [SELECT ID,AccountId FROM AccountContactRelation WHERE Id =:ctRelationRecordRec ];
        Contact contact = [SELECT ID,AccountId FROM Contact WHERE Id = :recordId];
        if(contact.AccountId == ctRelation.AccountId){
            contact.AccountId = null;
            update contact;
            delete [SELECT ID FROM ACCOUNT WHERE Id =: ctRelation.AccountId];
        }else{
            delete ctRelation;
        }
        Set<Id> setId = new Set<Id>();
        List<AccountContactRelation> unidades = [
            SELECT Id, AccountId,Account.Name, Account.Phone,IsActive,Roles
            FROM AccountContactRelation
            WHERE ContactId = :recordId      
        ];
        for(AccountContactRelation act : unidades){
            setId.add(act.AccountId);
        }
        List<Account> ambientesByAccount = [
            SELECT Id,Name,(SELECT Id,Cobertura__c,Name,Comprimento__c,Grupo__c,LarguraDimensao__c,PeDireito__c,Tipo__c,Unidade__c,AreaEsquadrias__c,AreaAmbiente__c
            FROM Ambientes__r) FROM ACCOUNT 
            WHERE Id IN :setId 
            
        ];
        //
        return DW_ResponseHTTP.success(new Map<String, Object>{
            'response' => unidades,
            'ambientes' => ambientesByAccount

        });
    } catch (Exception e) {
        return JSON.serialize(DW_ResponseHTTP.errorObj(new List<String>{e.getMessage(), e.getStackTraceString()}));
    }
    
    }
    @AuraEnabled
    public static String getQuestionsByAmbienteUpdateResposta(String respostaId,String valorResultado){
        try {
            Resposta__c resposta = [SELECT ID,Resposta__c,Ambiente__c from Resposta__c WHERE iD =:respostaId];
            resposta.Resposta__c = valorResultado;
            update resposta;

            List<Resposta__c> respostaAmbienteList = [Select id,Observacao__c,RespostaRealizada__c,Ambiente__c,Unidade__c,Unidade__r.Name,Ambiente__r.Name,Pergunta__c,Pergunta__r.Categoria__c,Pergunta__r.TextoAjuda__c,Pergunta__r.Pergunta__C,Pergunta__r.ItemPrincipal__c,Pergunta__r.Subcategoria__c,Pergunta__r.Secao__c,Resposta__C FROM Resposta__c
            
        WHERE  (Ambiente__c = : resposta.Ambiente__c ) ];
            Ambiente__c ambiente =[select id,QuantidadeResposta__c,QuantidadeRespostasFinalizadas__c from Ambiente__c where Id =  :resposta.Ambiente__c ];
            return DW_ResponseHTTP.success(new Map<String, Object>{
                'respostaAmbienteList'=> respostaAmbienteList,
                'qtRespostas'=>ambiente
            });
        } catch (Exception e) {
            return JSON.serialize(DW_ResponseHTTP.errorObj(new List<String>{e.getMessage(), e.getStackTraceString()}));
        }
    }
    @AuraEnabled
    public static String getQuestionsByUnidadeUpdateResposta(String respostaId,String valorResultado){
        try {
            Resposta__c resposta = [SELECT ID,Resposta__c,Unidade__c,Ambiente__c,Ambiente__r.Ubs__c from Resposta__c WHERE iD =:respostaId];
            resposta.Resposta__c = valorResultado;
            update resposta;

            Set<String> setIdAmbientes = new Set<String>();
            String IdUnidade;
            List<Account> unidadeList = new List<Account>();
            if(resposta.Unidade__c != null){
                IdUnidade = resposta.Unidade__c;
            } else if(resposta.Ambiente__c != null){
                IdUnidade= resposta.Ambiente__r.Ubs__c;

            }
            List<Ambiente__c> ambienteList = [SELECT ID FROM Ambiente__c WHERE UBS__c =:IdUnidade];
            for(Ambiente__c ambiente :ambienteList ){
                setIdAmbientes.add(ambiente.Id);
            }

            
            List<Resposta__c> respostaAmbienteList = [Select id,Observacao__c,RespostaRealizada__c,Ambiente__c,Pergunta__r.ItemPrincipalPai__c,Unidade__c,Unidade__r.Name,Ambiente__r.Name,Pergunta__c,Pergunta__r.Categoria__c,Pergunta__r.TextoAjuda__c,Pergunta__r.Pergunta__C,Pergunta__r.ItemPrincipal__c,Pergunta__r.Subcategoria__c,Pergunta__r.Secao__c,Resposta__C FROM Resposta__c
        WHERE  (Unidade__c = : IdUnidade ) OR (Ambiente__c IN :setIdAmbientes)  ];
            return DW_ResponseHTTP.success(new Map<String, Object>{
                'respostaAmbienteList'=> respostaAmbienteList
            });
        } catch (Exception e) {
            return JSON.serialize(DW_ResponseHTTP.errorObj(new List<String>{e.getMessage(), e.getStackTraceString()}));
        }
    }
    @AuraEnabled
    public static String getQuestionsByUnidadeUpdateObs(String respostaId,String valorResultado){
        try {
            Resposta__c resposta = [SELECT ID,Resposta__c,Observacao__c,Unidade__c,Ambiente__c,Ambiente__r.Ubs__c from Resposta__c WHERE iD =:respostaId];
            resposta.Observacao__c = valorResultado;
            update resposta;

            Set<String> setIdAmbientes = new Set<String>();
            String IdUnidade;
            List<Account> unidadeList = new List<Account>();
            if(resposta.Unidade__c != null){
                IdUnidade = resposta.Unidade__c;
            } else if(resposta.Ambiente__c != null){
                IdUnidade= resposta.Ambiente__r.Ubs__c;

            }
            List<Ambiente__c> ambienteList = [SELECT ID FROM Ambiente__c WHERE UBS__c =:IdUnidade];
            for(Ambiente__c ambiente :ambienteList ){
                setIdAmbientes.add(ambiente.Id);
            }

            
            List<Resposta__c> respostaAmbienteList = [Select id,Observacao__c,RespostaRealizada__c,Ambiente__c,Pergunta__r.ItemPrincipalPai__c,Unidade__c,Unidade__r.Name,Ambiente__r.Name,Pergunta__c,Pergunta__r.Categoria__c,Pergunta__r.TextoAjuda__c,Pergunta__r.Pergunta__C,Pergunta__r.ItemPrincipal__c,Pergunta__r.Subcategoria__c,Pergunta__r.Secao__c,Resposta__C FROM Resposta__c
        WHERE  (Unidade__c = : IdUnidade ) OR (Ambiente__c IN :setIdAmbientes)  ];
            return DW_ResponseHTTP.success(new Map<String, Object>{
                'respostaAmbienteList'=> respostaAmbienteList
            });
        } catch (Exception e) {
            return JSON.serialize(DW_ResponseHTTP.errorObj(new List<String>{e.getMessage(), e.getStackTraceString()}));
        }
    }
    @AuraEnabled
    public static String getQuestionsByAmbiente(String recordId,String ambienteId){
        try {
            List<Resposta__c> respostaAmbienteList = [Select id,RespostaRealizada__c,Ambiente__c,Unidade__c,Unidade__r.Name,Ambiente__r.Name,Pergunta__c,Pergunta__r.Categoria__c,Pergunta__r.TextoAjuda__c,Pergunta__r.ItemPrincipalPai__c,Pergunta__r.Pergunta__C,Pergunta__r.ItemPrincipal__c,Pergunta__r.Subcategoria__c,Pergunta__r.Secao__c,Resposta__C FROM Resposta__c
        WHERE  (Ambiente__c = : ambienteId ) ];
        Ambiente__c ambiente =[select id,QuantidadeResposta__c,QuantidadeRespostasFinalizadas__c from Ambiente__c where Id =  :ambienteId ];
            return DW_ResponseHTTP.success(new Map<String, Object>{
                'respostaAmbienteList'=> respostaAmbienteList,
                'qtRespostas'=>ambiente
            });
        } catch (Exception e) {
            return JSON.serialize(DW_ResponseHTTP.errorObj(new List<String>{e.getMessage(), e.getStackTraceString()}));
        }
    }
    @AuraEnabled
    public static String getQuestionsByUnidade(String recordId,String unidadeId){
        try {
            Set<String> setIdAmbientes = new Set<String>();

            List<Ambiente__c> ambienteList = [SELECT ID FROM Ambiente__c WHERE UBS__c =:unidadeId];
            for(Ambiente__c ambiente :ambienteList ){
                setIdAmbientes.add(ambiente.Id);
            }
            List<Resposta__c> respostaAmbienteList = [Select id,Observacao__c,RespostaRealizada__c,Ambiente__c,Pergunta__r.ItemPrincipalPai__c,Unidade__c,Unidade__r.Name,Ambiente__r.Name,Pergunta__c,Pergunta__r.Categoria__c,Pergunta__r.TextoAjuda__c,Pergunta__r.Pergunta__C,Pergunta__r.ItemPrincipal__c,Pergunta__r.Subcategoria__c,Pergunta__r.Secao__c,Resposta__C FROM Resposta__c
        WHERE  (Unidade__c = : unidadeId ) OR (Ambiente__c IN :setIdAmbientes)  ];
            return DW_ResponseHTTP.success(new Map<String, Object>{
                'respostaAmbienteList'=> respostaAmbienteList
            });
        } catch (Exception e) {
            return JSON.serialize(DW_ResponseHTTP.errorObj(new List<String>{e.getMessage(), e.getStackTraceString()}));
        }
    }

    

    @AuraEnabled
    public static String getAnswersVinculoRecMethod(String recordId){
    try {
        
        Set<Id> setId = new Set<Id>();
        List<AccountContactRelation> unidades = [
            SELECT Id, AccountId,Account.Name, Account.Phone,IsActive,Roles
            FROM AccountContactRelation
            WHERE ContactId = :recordId      
        ];
        for(AccountContactRelation act : unidades){
            setId.add(act.AccountId);
        }
        List<Account> ambientesByAccount = [
            SELECT Id,Name,(SELECT Id,Cobertura__c,Name,Comprimento__c,Grupo__c,LarguraDimensao__c,PeDireito__c,Tipo__c,Unidade__c,AreaEsquadrias__c,AreaAmbiente__c
            FROM Ambientes__r) FROM ACCOUNT 
            WHERE Id IN :setId 
            
        ];
        SET<Id> setIdAmbiente = new Set<Id>();

        List<Ambiente__c> ambienteList = [SELECT ID FROM Ambiente__c WHERE UBS__c IN :setId];

        FOR(Ambiente__c ambiente : ambienteList ){
            setIdAmbiente.add(ambiente.Id);
        }
        List<Resposta__c> respostaAmbienteList = [Select id,Observacao__c,RespostaRealizada__c,Ambiente__c,Unidade__c,Unidade__r.Name,Ambiente__r.Name,Pergunta__c,Pergunta__r.ItemPrincipalPai__c,Pergunta__r.Categoria__c,Pergunta__r.TextoAjuda__c,Pergunta__r.Pergunta__C,Pergunta__r.ItemPrincipal__c,Pergunta__r.Subcategoria__c,Pergunta__r.Secao__c,Resposta__C FROM Resposta__c
        WHERE  (Ambiente__c IN : setIdAmbiente ) ];

        //
        return DW_ResponseHTTP.success(new Map<String, Object>{
            'ambientes' => ambientesByAccount,
            'respostaAmbienteList'=> respostaAmbienteList
        });
    } catch (Exception e) {
        return JSON.serialize(DW_ResponseHTTP.errorObj(new List<String>{e.getMessage(), e.getStackTraceString()}));
    }
    
    }

    @AuraEnabled
    public static String accountVinculoRecMethod(String recordId,String accRecordRec){
    try {
        
        Contact contact = [SELECT ID,AccountId FROM Contact WHERE Id = :recordId];
        if(contact.AccountId == null){
            contact.AccountId =accRecordRec;
            update contact;
        }else{
            AccountContactRelation acr = new AccountContactRelation();
        acr.AccountId = accRecordRec;
        acr.ContactId = contact.Id;
        insert acr;
        }
        
        Set<Id> setId = new Set<Id>();
        List<AccountContactRelation> unidades = [
            SELECT Id, AccountId,Account.Name, Account.Phone,IsActive,Roles
            FROM AccountContactRelation
            WHERE ContactId = :recordId      
        ];
        for(AccountContactRelation act : unidades){
            setId.add(act.AccountId);
        }
        List<Account> ambientesByAccount = [
            SELECT Id,Name,(SELECT Id,Cobertura__c,Name,Comprimento__c,Grupo__c,LarguraDimensao__c,PeDireito__c,Tipo__c,Unidade__c,AreaEsquadrias__c,AreaAmbiente__c
            FROM Ambientes__r) FROM ACCOUNT 
            WHERE Id IN :setId 
            
        ];
        //
        return DW_ResponseHTTP.success(new Map<String, Object>{
            'response' => unidades,
            'ambientes' => ambientesByAccount
        });
    } catch (Exception e) {
        return JSON.serialize(DW_ResponseHTTP.errorObj(new List<String>{e.getMessage(), e.getStackTraceString()}));
    }
    
    }

    @AuraEnabled
    public static String createAmbienteRecMethod(String recordId,String accRecId,Ambiente__c ambienteRecord){
    try {
        insert ambienteRecord;
        
        Set<Id> setId = new Set<Id>();
        List<AccountContactRelation> unidades = [
            SELECT Id, AccountId,Account.Name, Account.Phone,IsActive,Roles
            FROM AccountContactRelation
            WHERE ContactId = :recordId      
        ];
        for(AccountContactRelation act : unidades){
            setId.add(act.AccountId);
        }
        List<Account> ambientesByAccount = [
            SELECT Id,Name,(SELECT Id,Cobertura__c,Name,Comprimento__c,Grupo__c,LarguraDimensao__c,PeDireito__c,Tipo__c,Unidade__c,AreaEsquadrias__c,AreaAmbiente__c
            FROM Ambientes__r) FROM ACCOUNT 
            WHERE Id IN :setId 
            
        ];
   
        return JSON.serialize(DW_ResponseHTTP.successObj(new Map<String, Object>{'ambientes' => ambientesByAccount}));
    } catch (Exception e) {
        return JSON.serialize(DW_ResponseHTTP.errorObj(new List<String>{e.getMessage(), e.getStackTraceString()}));
    }
    
    }

    @AuraEnabled
    public static String accountRecMethod(String recordId,Account accRec){
    try {
        accRec.CodigoExterno__c = accRec.Name;
        insert accRec;
        Contact contact = [SELECT ID,AccountId FROM Contact WHERE Id = :recordId];
        contact.AccountId =accRec.Id;
        update contact;

        List<AccountContactRelation> unidades = [
                SELECT Id, Account.Name, Account.Phone
                FROM AccountContactRelation
                WHERE ContactId = :recordId      
            ];
        //
        return DW_ResponseHTTP.success(new Map<String, Object>{
            'response' => unidades,
            'account' => accRec
        });
    } catch (Exception e) {
        return JSON.serialize(DW_ResponseHTTP.errorObj(new List<String>{e.getMessage(), e.getStackTraceString()}));
    }
    
    }

    @AuraEnabled(cacheable=true)
    public static String getUnidadesByContact(String recordId){
        try {
            
            List<AccountContactRelation> unidades = [
                SELECT Id, Account.Name, Account.Phone,IsActive,Roles
                FROM AccountContactRelation
                WHERE ContactId = :recordId      
            ];

            
            
            
            return JSON.serialize(DW_ResponseHTTP.successObj(new Map<String, Object>{
                'response' => unidades
            }));
        } catch (Exception e) {
            return JSON.serialize(DW_ResponseHTTP.errorObj(new List<String>{e.getMessage(), e.getStackTraceString()}));
        }
    }
    @AuraEnabled(cacheable=true)
    public static String getAmbientesByAccount(String accountId){
        try {
            
            List<Account> ambientesByAccount = [
                SELECT Id,Name,(SELECT Id,Cobertura__c,Name,Comprimento__c,Grupo__c,LarguraDimensao__c,PeDireito__c,Tipo__c,Unidade__c,AreaEsquadrias__c,AreaAmbiente__c
                FROM Ambientes__r) FROM ACCOUNT
                WHERE Id = :accountId 
            ];
            
            return JSON.serialize(DW_ResponseHTTP.successObj(new Map<String, Object>{'response' => ambientesByAccount}));
        } catch (Exception e) {
            return JSON.serialize(DW_ResponseHTTP.errorObj(new List<String>{e.getMessage(), e.getStackTraceString()}));
        }
    }
    @AuraEnabled(cacheable=true)
    public static String getAmbientesByContact(String recordId){
        try {

            List<String> optionsAmbientes = new List<String>();
            Schema.DescribeFieldResult fieldResult = Ambiente__c.Tipo__c.getDescribe();
            List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            for( Schema.PicklistEntry f : ple)
            {
                optionsAmbientes.add(f.getValue());
            }  

            List<String> optionsCobertura = new List<String>();
            Schema.DescribeFieldResult fieldResultCobertura = Ambiente__c.Cobertura__c.getDescribe();
            List<Schema.PicklistEntry> pleCobertura = fieldResultCobertura.getPicklistValues();
            for( Schema.PicklistEntry f : pleCobertura)
            {
                optionsCobertura.add(f.getValue());
            }

            Set<Id> setId = new Set<Id>();
            List<AccountContactRelation> unidades = [
                SELECT Id, AccountId,Account.Name, Account.Phone,IsActive,Roles
                FROM AccountContactRelation
                WHERE ContactId = :recordId      
            ];
            for(AccountContactRelation act : unidades){
                setId.add(act.AccountId);
            }
            List<Account> ambientesByAccount = [
                SELECT Id,Name,(SELECT Id,Cobertura__c,Name,Comprimento__c,Grupo__c,LarguraDimensao__c,PeDireito__c,Tipo__c,Unidade__c,AreaEsquadrias__c,AreaAmbiente__c
                FROM Ambientes__r) FROM ACCOUNT 
                WHERE Id IN :setId 
                
            ];
            
            return JSON.serialize(DW_ResponseHTTP.successObj(new Map<String, Object>{'ambientes' => ambientesByAccount,'optionsAmbientes' => optionsAmbientes,'optionsCobertura'=> optionsCobertura}));
        } catch (Exception e) {
            return JSON.serialize(DW_ResponseHTTP.errorObj(new List<String>{e.getMessage(), e.getStackTraceString()}));
        }
    }
    
 @AuraEnabled
    public static String accountDeleteAmbiente(String ambienteId,String recordId){
    try {
        
        
        delete [SELECT ID,Ubs__c FROM Ambiente__c WHERE Id = :ambienteId];

        Set<Id> setId = new Set<Id>();
            List<AccountContactRelation> unidades = [
                SELECT Id, AccountId,Account.Name, Account.Phone,IsActive,Roles
                FROM AccountContactRelation
                WHERE ContactId = :recordId      
            ];
            for(AccountContactRelation act : unidades){
                setId.add(act.AccountId);
            }
            List<Account> ambientesByAccount = [
                SELECT Id,Name,(SELECT Id,Cobertura__c,Name,Comprimento__c,Grupo__c,LarguraDimensao__c,PeDireito__c,Tipo__c,Unidade__c,AreaEsquadrias__c,AreaAmbiente__c
                FROM Ambientes__r) FROM ACCOUNT 
                WHERE Id IN :setId 
                
            ];
       
            return JSON.serialize(DW_ResponseHTTP.successObj(new Map<String, Object>{'ambientes' => ambientesByAccount}));
       
    } catch (Exception e) {
        return JSON.serialize(DW_ResponseHTTP.errorObj(new List<String>{e.getMessage(), e.getStackTraceString()}));
    }
    
    }
    @AuraEnabled
    public static string sendEmailToController(String toSend){
        try{
            Contact[] getContact =[SELECT ID,EMAIL,senha__c,EnviarEmailRecuperacao__c FROM CONTACT WHERE EMAIL = :toSend];
            if(getContact.size()==0){
                return JSON.serialize(DW_ResponseHTTP.errorObj(new List<String>{'não foi encontrado nenhum usuario com esse email', 'não foi encontrado nenhum usuario com esse email'}));
 
            }
            getContact[0].EnviarEmailRecuperacao__c = true;
            update getContact;

            return JSON.serialize(DW_ResponseHTTP.successObj(new Map<String, Object>{'enviado' => 'enviado'}));
        }catch(Exception e){
            return JSON.serialize(DW_ResponseHTTP.errorObj(new List<String>{e.getMessage(), e.getStackTraceString()}));

        }
    }
}