objects/IntegracaoERP__mdt.object
<CustomObject>
    <label>Integração ERP</label>
    <pluralLabel>Integrações ERP</pluralLabel>
    <fields>
        <fullName>Ativo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ativo</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

classes/MetadataHelper.cls
public without sharing class MetadataHelper {
    Map<String, String> stringMap = new Map<String, String>();
    private static final MetadataHelper instance = new MetadataHelper();
    public IntegracaoERP__mdt integracaoERP;


    public static MetadataHelper getInstance(){
       
        if (instance.integracaoERP == null) {
            instance.integracaoERP = (IntegracaoERP__mdt)DW_QueryFactory.get('IntegracaoERP__mdt')
                .setCondition(DW_QueryCondition.newInstance('Ativo__c', '=',true))
                .run()
                .get(0);
        }
        return instance;
    }
}